# Generated by Django 5.0.7 on 2024-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_dislike_remove_post_like_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
