# Generated by Django 5.0.7 on 2024-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_dislikes_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_modified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
