# Generated by Django 5.0.7 on 2024-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_is_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_modified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
