# Generated by Django 5.0.7 on 2024-08-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_reply_is_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
